### PR TITLE
reviewed and merged the existing PRs

### PR DESCRIPTION
**Pull request by treaz**
@julienrf here's the PR that you asked in https://github.com/treaz/progfun-wiki/pull/1

### CODE REVIEW

**Comment by julienrf** [comment]
Thanks, do you mind also including my PR? (treaz#1)

**Comment by treaz** [comment]
done

**Comment by treaz** [comment]
@julienrf I've got some extra free time on my hands these days. And I would like to keep the cheatsheet up to date (as I'm learning scala right now and it's super useful). Would you be willing to give me rights to merge PRs?

**Comment by julienrf** [comment]
@treaz Sure! Invitation sent ;)

**Review by julienrf — APPROVED** [review]

**Comment by treaz** [comment]
@julienrf since I've already reviewed most of those PRs I'll close the ones that I've reviewed and take a look over the ones that are left

**Comment by julienrf** [comment]
Awesome, thank you so much!

**Pull request merged**
