### PR TITLE
Added a pattern matching example to handle Option

### PR DESCRIPTION
**Pull request by lpoulain**
Added a pattern matching example to handle functions that return a type Option[T]

### CODE REVIEW

**Comment by gzm0** [comment]
Hey,

Thanks for the addition. Personally I think something like the following is much more idiomatic for `Option` types: 

```
def getMapValue(s: String): String = 
    myMap.get(s).map("Value found " + _).getOrElse("No Value found")
```

What do you folks think?

**Comment by lpoulain** [comment]
This works in the case of map. But what about other functions that return an Option? I ran into that issue in the latest assignment.

**Comment by lrytz** [comment]
Hi Laurent,

I'd be interested to see the problem you ran into, if you can re-construct it!

In general, pattern matching on options is OK, it's often easier to write and understand, but a bit more verbose than using combinator functions. So we could show both to make a good example.

Thanks!
Lukas

**Comment by lpoulain** [comment]
I got an Option[T] as the result of a List.find() call. Pattern matching seemed like the best way to deal with that result, but I'm interested if there is any other way to process an Option[].

**Comment by lpoulain** [comment]
Note that I put the Option[] in the pattern matching section as it's the same treatment of a not-fully-determined type (the original section name was actually "Runtime type check")

**Comment by lrytz** [comment]
Most of the times when you pattern match an option, the same can be expressed with some method calls on that option. There are a lot of examples here (you can skip reading the text): http://blog.tmorris.net/scalaoption-cheat-sheet/

**Comment by lpoulain** [comment]
Good to know. So I guess it doesn't make sense to talk about Option in the pattern matching section, except maybe to say it's recommended to use other methods. Although I'm still not sure how to handle the result of a List.find() without pattern matching ;-)

**Comment by lrytz** [comment]
I would not say it doesn't make sense - it's just often not the most elegant solution, but it's not like mutable state or something like that.

About List.find(), depends what you want to do with the result, and what to do in case there is no such element! Example:

```
val r = List(1,2).find(x => x > 1) // r = Some(2)
r.foreach(x => println("found number > 1 : " + x)
```

**Comment by lpoulain** [comment]
I am using find() when implementing the subtract function to find the first (and only) tuple with the right key (first element) so I can get the second element. But we're getting outside of the scope of the thread.

**Comment by lrytz** [comment]
You're right about the scope of the thread :) But: if you know that `find` will succeed, then you can just call `list.find(...).get`. `get` will throw an exception if the receiver is `None`.

**Comment by gzm0** [comment]
We should definitely put in some information about this. Lukas: I'll pull this to a topic branch and make a proposition.

**Comment by gzm0** [comment]
Proposal is in branch topic/option. @lrytz please review.

**Comment by lrytz** [comment]
i created a new pull #9 from your branch, so closing this one

**Comment by gzm0** [comment]
Ohhh... I wanted to check if gh closes this one once we merge the topic back... :(

**Pull request closed without merging**
